inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'expressir.gemspec'
    - 'original/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'
    - 'exe/format-test'
#    - 'lib/expressir/cli/**/*'
    - 'lib/expressir/express/**/*'
    - 'lib/expressir/model/**/*'

Style/RedundantParentheses:
  Exclude:
    - 'rakelib/cross-ruby.rake'

Layout/LineLength:
  Max: 160
