name: release

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  pack:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.4'

      - if: matrix.os == 'macos-latest'
        run: brew install autoconf automake libtool

      - run: bundle install --jobs 4 --retry 3

      - run: bundle exec rake native gem

      - run: bundle exec rake

      - uses: actions/upload-artifact@v2
        with:
          name: pkg-${{ matrix.os }}
          path: pkg/*.gem

  release:
    runs-on: ubuntu-18.04
    needs: pack
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: pkg-ubuntu-latest
          path: pkg

      - uses: actions/download-artifact@v2
        with:
          name: pkg-windows-latest
          path: pkg

      - uses: actions/download-artifact@v2
        with:
          name: pkg-macos-latest
          path: pkg

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.4'

      - run: ls -l pkg/

      - name: Publish to rubygems.org
        env:
          RUBYGEMS_API_KEY: ${{secrets.LUTAML_CI_RUBYGEMS_API_KEY}}
        run: |
          mkdir -p ~/.gem
          echo "--" > ~/.gem/credentials
          echo ":rubygems_api_key: ${RUBYGEMS_API_KEY}" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem signin
          for gem in pkg/*.gem; do gem push $gem -V -k rubygems ; done
