name: stress

on:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

env:
  BUNDLER_VER: 2.4.22
  GC_STRESS: true

jobs:
  rake:
    name: test on ruby-${{ matrix.ruby }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.2', '3.1', '3.0', '2.7' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup packages
        if: startsWith(matrix.os, 'macos')
        run: brew install autoconf automake libtool

      - name: Install Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ env.BUNDLER_VER }}
          # Rice gem has issues with bundler cache
          # more info https://github.com/lutaml/expressir/runs/2097658383?check_suite_focus=true#step:7:2126
          # but it is not the only issue
          bundler-cache: false

      - name: Bundle
        run: bundle install --jobs 4 --retry 3

      - name: Build native extension
        run: bundle exec rake compile

      - name: Run tests
        run: |
          bundle exec rake
          cat .rspec_status
